/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Busqueda.VistaBusqueda;
import Control.*;
import General.Utilidades;
import Modelo.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author MERRY
 */
public class VistaAgregarEntrada extends javax.swing.JFrame {
    public int banBQDElementos = 0;
    public String idElemento = "";
    public String cantAnterior = "";
    public int idEntrada = 0;//36562514PLUS
    public int InsertElemento = 0;
    public int InsertEntrada = 0;
    public ModeloVentanaGeneral objetoVentana;
    public ModeloGestorBusqueda objetoBusqueda;
    public ModeloElemento modeloElemento;
    public ModeloEntrada modeloEntrada;
    public ControlElemento controlElemento;
    public ControlEntrada controlEntrada;
    public ControlInventario controlInventario;
    public ArrayList<ModeloElemento>  ListamodeloElemento;
    public VistaEntradas ve;
    /**
     * Creates new form VistaAgregarEntrada
     */
    public VistaAgregarEntrada() {
        initComponents();
        controlElemento = new ControlElemento();
        controlEntrada = new ControlEntrada();
        controlInventario = new ControlInventario();
        LimpiarFormulario();
        ListarElementos();
        
    }

    VistaAgregarEntrada(VistaEntradas ve) {
        initComponents();
        this.ve = ve;
        controlElemento = new ControlElemento();
        controlEntrada = new ControlEntrada();
        controlInventario = new ControlInventario();
        LimpiarFormulario();
        ListarElementos();
    }
    
    VistaAgregarEntrada(VistaEntradas ve, ModeloEntrada modelo) throws ParseException {
        initComponents();
        this.ve = ve;
        
        controlElemento = new ControlElemento();
        controlEntrada = new ControlEntrada();
        controlInventario = new ControlInventario();
        LimpiarFormulario();
        ListarElementos();
        this.modeloEntrada = modelo;
        LlenarFormulario(); 
        InhabilitarElementos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlElemento = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblBsqElementos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtConcentracion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtPresentacionComercial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cbSemaforizacion = new javax.swing.JComboBox();
        txtRegistroSanitario = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbRiesgo = new javax.swing.JComboBox();
        jdFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jdFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jdFechaFinal = new com.toedter.calendar.JDateChooser();
        jSeparator9 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jdFechaEntrada = new com.toedter.calendar.JDateChooser();
        pnlLimpiar = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        pnlGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 108, 151));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar Entrada");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.ipadx = 433;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 22);
        jPanel1.add(jLabel7, gridBagConstraints);

        pnlElemento.setBackground(new java.awt.Color(255, 255, 255));
        pnlElemento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elemento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(22, 108, 151))); // NOI18N
        pnlElemento.setLayout(new java.awt.GridBagLayout());

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(22, 108, 151));
        txtDescripcion.setText("rsrd");
        txtDescripcion.setBorder(null);
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 0);
        pnlElemento.add(txtDescripcion, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 108, 151));
        jLabel1.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 0, 0);
        pnlElemento.add(jLabel1, gridBagConstraints);

        jSeparator2.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 319;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 16, 0, 0);
        pnlElemento.add(jSeparator2, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 108, 151));
        jLabel2.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 0, 0);
        pnlElemento.add(jLabel2, gridBagConstraints);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(22, 108, 151));
        txtCodigo.setText("rsrd");
        txtCodigo.setBorder(null);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 0, 10);
        pnlElemento.add(txtCodigo, gridBagConstraints);

        jSeparator3.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 10);
        pnlElemento.add(jSeparator3, gridBagConstraints);

        lblBsqElementos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_1.png"))); // NOI18N
        lblBsqElementos.setToolTipText("Consultar Arrendatario");
        lblBsqElementos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBsqElementos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqElementosMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlElemento.add(lblBsqElementos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 22);
        jPanel1.add(pnlElemento, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 108, 151));
        jLabel3.setText("Lote");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLote.setForeground(new java.awt.Color(22, 108, 151));
        txtLote.setText("rsrd");
        txtLote.setBorder(null);
        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });
        txtLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoteFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(txtLote, gridBagConstraints);

        jSeparator4.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(jSeparator4, gridBagConstraints);

        txtConcentracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConcentracion.setForeground(new java.awt.Color(22, 108, 151));
        txtConcentracion.setText("rsrd");
        txtConcentracion.setBorder(null);
        txtConcentracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcentracionActionPerformed(evt);
            }
        });
        txtConcentracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConcentracionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(txtConcentracion, gridBagConstraints);

        jSeparator5.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 71, 0, 0);
        jPanel1.add(jSeparator5, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 108, 151));
        jLabel4.setText("CONCENTRACIÓN Y SERIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 71, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 108, 151));
        jLabel5.setText("Marca/Laboratorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 50, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(22, 108, 151));
        txtMarca.setText("rsrd");
        txtMarca.setBorder(null);
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        txtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMarcaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(txtMarca, gridBagConstraints);

        jSeparator6.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(jSeparator6, gridBagConstraints);

        txtPresentacionComercial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPresentacionComercial.setForeground(new java.awt.Color(22, 108, 151));
        txtPresentacionComercial.setText("rsrd");
        txtPresentacionComercial.setBorder(null);
        txtPresentacionComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentacionComercialActionPerformed(evt);
            }
        });
        txtPresentacionComercial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPresentacionComercialFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(txtPresentacionComercial, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(22, 108, 151));
        jLabel6.setText("Presentación Comercial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 71, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jSeparator7.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 71, 0, 0);
        jPanel1.add(jSeparator7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(22, 108, 151));
        jLabel8.setText("Clasificación de Riesgo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 50, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        cbSemaforizacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSemaforizacion.setForeground(new java.awt.Color(22, 108, 151));
        cbSemaforizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Verde", "Amarillo", "Rojo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(cbSemaforizacion, gridBagConstraints);

        txtRegistroSanitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRegistroSanitario.setForeground(new java.awt.Color(22, 108, 151));
        txtRegistroSanitario.setText("rsrd");
        txtRegistroSanitario.setBorder(null);
        txtRegistroSanitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroSanitarioActionPerformed(evt);
            }
        });
        txtRegistroSanitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegistroSanitarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(txtRegistroSanitario, gridBagConstraints);

        jSeparator8.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 71, 0, 0);
        jPanel1.add(jSeparator8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(22, 108, 151));
        jLabel9.setText("Registro Sanitario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 71, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(22, 108, 151));
        jLabel10.setText("Semaforización");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 50, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(22, 108, 151));
        jLabel11.setText("Fecha Vencimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 71, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        cbRiesgo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbRiesgo.setForeground(new java.awt.Color(22, 108, 151));
        cbRiesgo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "I", "IIA", "IIB", "III" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(cbRiesgo, gridBagConstraints);

        jdFechaVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        jdFechaVencimiento.setForeground(new java.awt.Color(22, 108, 151));
        jdFechaVencimiento.setToolTipText("");
        jdFechaVencimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(jdFechaVencimiento, gridBagConstraints);

        jdFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        jdFechaInicio.setForeground(new java.awt.Color(22, 108, 151));
        jdFechaInicio.setToolTipText("");
        jdFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(jdFechaInicio, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(22, 108, 151));
        jLabel12.setText("Fecha Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(22, 108, 151));
        jLabel13.setText("Fecha Final");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 71, 0, 0);
        jPanel1.add(jLabel13, gridBagConstraints);

        jdFechaFinal.setBackground(new java.awt.Color(255, 255, 255));
        jdFechaFinal.setForeground(new java.awt.Color(22, 108, 151));
        jdFechaFinal.setToolTipText("");
        jdFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(jdFechaFinal, gridBagConstraints);

        jSeparator9.setForeground(new java.awt.Color(22, 108, 151));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(jSeparator9, gridBagConstraints);

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(22, 108, 151));
        txtCantidad.setText("rsrd");
        txtCantidad.setBorder(null);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(txtCantidad, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(22, 108, 151));
        jLabel14.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(22, 108, 151));
        jLabel15.setText("Fecha Entrada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 71, 0, 0);
        jPanel1.add(jLabel15, gridBagConstraints);

        jdFechaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        jdFechaEntrada.setForeground(new java.awt.Color(22, 108, 151));
        jdFechaEntrada.setToolTipText("");
        jdFechaEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 71, 0, 0);
        jPanel1.add(jdFechaEntrada, gridBagConstraints);

        pnlLimpiar.setBackground(new java.awt.Color(22, 108, 151));
        pnlLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLimpiarLayout = new javax.swing.GroupLayout(pnlLimpiar);
        pnlLimpiar.setLayout(pnlLimpiarLayout);
        pnlLimpiarLayout.setHorizontalGroup(
            pnlLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLimpiarLayout.createSequentialGroup()
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLimpiarLayout.setVerticalGroup(
            pnlLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLimpiarLayout.createSequentialGroup()
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 31, 20, 0);
        jPanel1.add(pnlLimpiar, gridBagConstraints);

        pnlGuardar.setBackground(new java.awt.Color(22, 108, 151));
        pnlGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGuardarLayout = new javax.swing.GroupLayout(pnlGuardar);
        pnlGuardar.setLayout(pnlGuardarLayout);
        pnlGuardarLayout.setHorizontalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarLayout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlGuardarLayout.setVerticalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarLayout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 23, 20, 0);
        jPanel1.add(pnlGuardar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistroSanitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegistroSanitarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroSanitarioFocusLost

    private void txtRegistroSanitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroSanitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroSanitarioActionPerformed

    private void txtPresentacionComercialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPresentacionComercialFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentacionComercialFocusLost

    private void txtPresentacionComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentacionComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentacionComercialActionPerformed

    private void txtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarcaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFocusLost

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtConcentracionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConcentracionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracionFocusLost

    private void txtConcentracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcentracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracionActionPerformed

    private void txtLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteFocusLost

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        ValidarCodigoElemento();
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusLost
        
    }//GEN-LAST:event_txtDescripcionFocusLost

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadFocusLost

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        Utilidades.establecerColorDeFondo(pnlGuardar, true);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        Utilidades.establecerColorDeFondo(pnlGuardar, false);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(InsertEntrada == 0)
            GuardarEntrada();
        else 
            ModificarEntrada();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        Utilidades.establecerColorDeFondo(pnlLimpiar, true);
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        Utilidades.establecerColorDeFondo(pnlLimpiar, false);
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void lblBsqElementosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqElementosMouseClicked
        if (banBQDElementos == 0) {
            banBQDElementos = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if (lblBsqElementos.isEnabled()) {
                objetoBusqueda = new ModeloGestorBusqueda(jPanel1, "BQD_ELEM", 1);
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_lblBsqElementosMouseClicked

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            ValidarCodigoElemento(); 
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgregarEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbRiesgo;
    private javax.swing.JComboBox cbSemaforizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jdFechaEntrada;
    private com.toedter.calendar.JDateChooser jdFechaFinal;
    private com.toedter.calendar.JDateChooser jdFechaInicio;
    private com.toedter.calendar.JDateChooser jdFechaVencimiento;
    private javax.swing.JLabel lblBsqElementos;
    private javax.swing.JPanel pnlElemento;
    private javax.swing.JPanel pnlGuardar;
    private javax.swing.JPanel pnlLimpiar;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtConcentracion;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtLote;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtPresentacionComercial;
    public javax.swing.JTextField txtRegistroSanitario;
    // End of variables declaration//GEN-END:variables

    public void ListarElementos(){
        ListamodeloElemento = (ArrayList<ModeloElemento>) controlElemento.ObtenerDatos();
    }
    
    public void RetornoBusqueda(ModeloGestorBusqueda objeto, Map<String, String> retorno) {
        if (objeto.getOpcion() == 0) {// DEFAULT VISTA__VENTANA__

        } else if (objeto.getOpcion() == 1) {// AGREGAR ELEMENTOS
            banBQDElementos = 0;
            idElemento = retorno.get("ID");
            txtDescripcion.setText("" + retorno.get("DESCRIPCION"));
            txtCodigo.setText("" + retorno.get("CODIGO"));
            txtLote.requestFocus();
        }
    }

    private void ValidarCodigoElemento() {
        String codigo = txtCodigo.getText().trim();
        if(!codigo.equals("")){
            for(int i = 0; i < ListamodeloElemento.size(); i++){
                if(ListamodeloElemento.get(i).getCodigo_elemento().equals(codigo)){
                    InsertElemento = 1;
                    idElemento = ListamodeloElemento.get(i).getId();
                    txtDescripcion.setText(ListamodeloElemento.get(i).getDescripcion_elemento());
                    txtLote.requestFocus();
                    break;
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Por favor escriba el codigo.");
            txtCodigo.requestFocusInWindow();
        }
    }

    private void LimpiarFormulario() {
        InsertElemento = 0;
        InsertEntrada = 0;
        idElemento = "";
        txtCantidad.setText("");
        txtCodigo.setText("");
        txtConcentracion.setText("");
        txtDescripcion.setText("");
        txtLote.setText("");
        txtMarca.setText("");
        txtPresentacionComercial.setText("");
        txtRegistroSanitario.setText("");
        cbRiesgo.setSelectedIndex(0);
        cbSemaforizacion.setSelectedIndex(0);
        
        
        modeloElemento = new ModeloElemento();
        modeloElemento.setId("0");
        modeloElemento.setFecha("NOW()");
        modeloElemento.setId_usuario("0");
        
        modeloEntrada = new ModeloEntrada();
        modeloEntrada.setId("0");
        modeloEntrada.setFecha("NOW()");
        modeloEntrada.setId_usuario("0");
        
        IniciarFechaEntrada();
        IniciarFechaFinal();
        IniciarFechaInicio();
        IniciarFechaVencimiento();
    }

    private void GuardarEntrada() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar fechaVencimiento = jdFechaVencimiento.getCalendar();
        Calendar fechaEntrada = jdFechaEntrada.getCalendar();
        Calendar fechaInicio = jdFechaInicio.getCalendar();
        Calendar fechaFinal = jdFechaFinal.getCalendar();
        String descripcion = txtDescripcion.getText().trim();
        String codigo = txtCodigo.getText().trim();
        String lote = txtLote.getText().trim();
        String concentracion = txtConcentracion.getText().trim();
        String marca = txtMarca.getText().trim();
        String presentacion = txtPresentacionComercial.getText().trim();
        String registro = txtRegistroSanitario.getText().trim();
        String cantidad = txtCantidad.getText().trim();
        String riesgo = ""+cbRiesgo.getSelectedItem();
        String semaforizacion = ""+cbSemaforizacion.getSelectedItem();
        
        //validaciones
//        if(Double.parseDouble(AreaFinca) < AcuAreaBloques+AreaTo){
//            JOptionPane.showMessageDialog(this, "El area debe ser menor al area total de la finca");
//            return;
//        }
        int retEle = -1;
        idElemento = modeloElemento.getId();
        if(InsertElemento == 0){//INGRESAR ELEMENTO
            modeloElemento.setCodigo_elemento(codigo);
            modeloElemento.setDescripcion_elemento(descripcion);
            retEle = controlElemento.Guardar(modeloElemento);
            
            if(retEle == 0){
                idElemento = controlElemento.getID(descripcion, codigo);
                modeloElemento.setId(idElemento);
            }
            
        }
        
        modeloEntrada.setCantidad(cantidad);
        modeloEntrada.setCodigo_elemento(codigo);
        modeloEntrada.setConcentracion(concentracion);
        modeloEntrada.setDescripcion_elemento(descripcion);
        modeloEntrada.setFecha("NOW()");
        modeloEntrada.setFecha_entrada(sdf.format(fechaEntrada.getTime()));
        modeloEntrada.setFecha_fin(sdf.format(fechaFinal.getTime()));
        modeloEntrada.setFecha_inicio(sdf.format(fechaInicio.getTime()));
        modeloEntrada.setFecha_vencimiento(sdf.format(fechaVencimiento.getTime()));
        modeloEntrada.setId_elemento(idElemento);
        modeloEntrada.setLote(lote);
        modeloEntrada.setMarca(marca);
        modeloEntrada.setPresentacion(presentacion);
        modeloEntrada.setReg_sanitario(registro);
        modeloEntrada.setRiesgo(riesgo);
        modeloEntrada.setSemaforizacion(semaforizacion); 
        
        int retEnt = -1;
        retEnt = controlEntrada.Guardar(modeloEntrada);
        if(retEle == 0){
            ActualizarElementos();
        }
        
        if(retEnt == 0){
            controlInventario.ActualizarInventario(0, idElemento, modeloEntrada.getCantidad(), InsertElemento);
            int resp = JOptionPane.showConfirmDialog(null, "Operación Realizada con exito.\n Desea ingresar otra entrada?","Agregar entrada",JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                ve.RespuestaAgregarEntrada();
                LimpiarFormulario();
                ListarElementos();
            }else{
                LimpiarFormulario();
                this.dispose();
                ve.RespuestaAgregarEntrada();
                ve.requestFocus();
            }
        }
    }
      
    public void IniciarFechaVencimiento(){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaVencimiento.setCalendar(Calendar.getInstance());    
    }
    public void IniciarFechaEntrada(){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaEntrada.setCalendar(Calendar.getInstance());    
    }
    public void IniciarFechaInicio(){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaInicio.setCalendar(Calendar.getInstance());    
    }
    public void IniciarFechaFinal(){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaFinal.setCalendar(Calendar.getInstance());    
    }

    private void ActualizarElementos() {
        ListamodeloElemento.add(modeloElemento);
    }

    private void ModificarEntrada() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar fechaVencimiento = jdFechaVencimiento.getCalendar();
        Calendar fechaEntrada = jdFechaEntrada.getCalendar();
        Calendar fechaInicio = jdFechaInicio.getCalendar();
        Calendar fechaFinal = jdFechaFinal.getCalendar();
        String descripcion = txtDescripcion.getText().trim();
        String codigo = txtCodigo.getText().trim();
        String lote = txtLote.getText().trim();
        String concentracion = txtConcentracion.getText().trim();
        String marca = txtMarca.getText().trim();
        String presentacion = txtPresentacionComercial.getText().trim();
        String registro = txtRegistroSanitario.getText().trim();
        String cantidad = txtCantidad.getText().trim();
        String riesgo = ""+cbRiesgo.getSelectedItem();
        String semaforizacion = ""+cbSemaforizacion.getSelectedItem();
        
        modeloEntrada.setCantidad(cantidad);
        modeloEntrada.setCodigo_elemento(codigo);
        modeloEntrada.setConcentracion(concentracion);
        modeloEntrada.setDescripcion_elemento(descripcion);
        modeloEntrada.setFecha("NOW()");
        modeloEntrada.setFecha_entrada(sdf.format(fechaEntrada.getTime()));
        modeloEntrada.setFecha_fin(sdf.format(fechaFinal.getTime()));
        modeloEntrada.setFecha_inicio(sdf.format(fechaInicio.getTime()));
        modeloEntrada.setFecha_vencimiento(sdf.format(fechaVencimiento.getTime()));
        modeloEntrada.setId_elemento(idElemento);
        modeloEntrada.setLote(lote);
        modeloEntrada.setMarca(marca);
        modeloEntrada.setPresentacion(presentacion);
        modeloEntrada.setReg_sanitario(registro);
        modeloEntrada.setRiesgo(riesgo);
        modeloEntrada.setSemaforizacion(semaforizacion); 
        
        int retEnt = -1;
        retEnt = controlEntrada.Actualizar(modeloEntrada);
        
        if(retEnt == 0){
            String cant = "" + (Integer.parseInt(modeloEntrada.getCantidad()) - Integer.parseInt(cantAnterior));
            controlInventario.ActualizarInventario(0, idElemento, cant, InsertElemento);
            JOptionPane.showMessageDialog(null, "Operación Realizada con exito.\n ");
            LimpiarFormulario();
            this.dispose();
            ve.RespuestaAgregarEntrada();
            ve.requestFocus();
            
        }
        
    }

    private void LlenarFormulario() throws ParseException {
        InsertElemento = 1;
        InsertEntrada = 1;
        idElemento = modeloEntrada.getId_elemento();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        cantAnterior = ""+modeloEntrada.getCantidad();
        txtCantidad.setText(""+modeloEntrada.getCantidad());
        txtCodigo.setText(""+modeloEntrada.getCodigo_elemento());
        txtConcentracion.setText(""+modeloEntrada.getConcentracion());
        txtDescripcion.setText(""+modeloEntrada.getDescripcion_elemento());
        txtLote.setText(""+modeloEntrada.getLote());
        txtMarca.setText(""+modeloEntrada.getMarca());
        txtPresentacionComercial.setText(""+modeloEntrada.getPresentacion());
        txtRegistroSanitario.setText(""+modeloEntrada.getReg_sanitario());
        cbRiesgo.setSelectedItem(""+modeloEntrada.getRiesgo());
        cbSemaforizacion.setSelectedItem(""+modeloEntrada.getSemaforizacion());
        
        
        jdFechaVencimiento.setDate(formato.parse(modeloEntrada.getFecha_vencimiento()));
        jdFechaEntrada.setDate(formato.parse(modeloEntrada.getFecha_entrada()));
        jdFechaInicio.setDate(formato.parse(modeloEntrada.getFecha_inicio()));  
        jdFechaFinal.setDate(formato.parse(modeloEntrada.getFecha_fin()));   
    }

    private void InhabilitarElementos() {
        txtCodigo.setEnabled(false);
        txtDescripcion.setEnabled(false);
        banBQDElementos = 1;
        lblBsqElementos.setEnabled(false);
    }
}
